### PR TITLE
Added totally flawless and complete implementation of state, city, ye…

### PR DESCRIPTION
**Pull request by JSteilberg**
…ar, month, day, email for user

### CODE REVIEW

**Review by kakade-o — CHANGES_REQUESTED** [review]
The birthday (day, month, year) should be a drop down. We can't have users type in bogus strings as their birthday. Otherwise, the code looks good.

Please address this bug.

**Comment by JSteilberg** [comment]
Reassigning to tgrauslys

**Comment by JSteilberg** [comment]
Let's get this out for now, and add a full calendar later.

**Review by kakade-o — APPROVED** [review]

**Comment by kakade-o** [comment]
Ok

**Pull request merged**
